# Generated by Django 4.2.2 on 2023-06-25 15:04

import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0003_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=30, validators=[django.contrib.auth.password_validation.validate_password, django.core.validators.RegexValidator(message='Password must contain at least 8 characters, including uppercase, lowercase, digits, and special characters.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_\\-+])[A-Za-z\\d!@#$%^&*()_\\-+]{8,}$')]),
        ),
    ]
