# Generated by Django 4.2.2 on 2023-06-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0006_alter_person_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='password_category',
        ),
    ]
