# Generated by Django 4.2.2 on 2023-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0007_rename_password_person_password_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password_category',
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1212, max_length=20),
            preserve_default=False,
        ),
    ]
