# Generated by Django 4.2.2 on 2023-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0008_remove_person_password_category_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
