# Generated by Django 4.2.2 on 2023-06-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0009_alter_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rate_success',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
