# Generated by Django 4.2.2 on 2023-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0010_alter_person_rate_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rate_success',
            field=models.IntegerField(default=0),
        ),
    ]
