# Generated by Django 4.2.2 on 2023-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0015_alter_person_likes_computer_vision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='good_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
